name = "ArenaPass"
uuid = "2505b373-b201-41d0-acc0-311690c44375"
authors = ["Artem Solod"]
version = "0.4.3"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1"
julia = "1.12"
